// Archivo centralizado de sucursales para DentalMas
// Puedes importar este archivo donde lo necesites



// Estados y municipios de México (solo algunos ejemplos, puedes expandir)
const estadosMunicipios = [
  { estado: 'CDMX', municipios: ['Benito Juárez', 'Coyoacán', 'Miguel Hidalgo'] },
  { estado: 'Nuevo León', municipios: ['Monterrey', 'San Nicolás', 'Guadalupe'] },
  { estado: 'Jalisco', municipios: ['Guadalajara', 'Zapopan', 'Tlaquepaque'] },
  { estado: 'Puebla', municipios: ['Puebla', 'Tehuacán'] },
  { estado: 'Querétaro', municipios: ['Querétaro'] },
  { estado: 'Quintana Roo', municipios: ['Cancún', 'Playa del Carmen'] },
  { estado: 'Yucatán', municipios: ['Mérida'] },
  { estado: 'Guanajuato', municipios: ['León'] },
  { estado: 'México', municipios: ['Toluca'] },
  { estado: 'Veracruz', municipios: ['Veracruz'] },
  { estado: 'Michoacán', municipios: ['Morelia'] },
  { estado: 'Aguascalientes', municipios: ['Aguascalientes'] },
  { estado: 'Chihuahua', municipios: ['Chihuahua'] },
  { estado: 'Sonora', municipios: ['Hermosillo'] },
  { estado: 'Chiapas', municipios: ['Tuxtla Gutiérrez'] },
];

const sucursales = [
  {
  nombre: "DentalMás Citadel",
    estado: "Nuevo León",
    municipio: "Monterrey",
    icon: "city",
    calificacion: 4.7,
    reviews: 92,
    direccion: "32.525151,-117.033252",
    telefono: "(664) 123-4567",
    horario: "Lunes a Viernes: 9:00 AM - 7:00 PM",
    maps: "https://www.google.com/maps/search/?api=1&query=32.525151,-117.033252",
    fotos: ["https://via.placeholder.com/300x200"],
  },
  {
  nombre: "DentalMás Reforma",
    estado: "CDMX",
    municipio: "Miguel Hidalgo",
    icon: "city",
    calificacion: 4.8,
    reviews: 120,
    direccion: "19.432608,-99.133209",
    telefono: "(55) 987-6543",
    horario: "Lunes a Sábado: 8:00 AM - 8:00 PM",
    maps: "https://www.google.com/maps/search/?api=1&query=19.432608,-99.133209",
    fotos: ["https://via.placeholder.com/300x200"],
  },
  {
  nombre: "DentalMás Monterrey",
    estado: "Nuevo León",
    municipio: "Monterrey",
    icon: "mountain",
    calificacion: 4.9,
    reviews: 150,
    direccion: "25.686614,-100.316113",
    telefono: "(81) 123-4567",
    horario: "Lunes a Domingo: 9:00 AM - 9:00 PM",
    maps: "https://www.google.com/maps/search/?api=1&query=25.686614,-100.316113",
    fotos: ["https://via.placeholder.com/300x200"],
  },
  {
  nombre: "DentalMás Guadalajara",
    estado: "Jalisco",
    municipio: "Guadalajara",
    icon: "tree",
    calificacion: 4.6,
    reviews: 80,
    direccion: "20.659698,-103.349609",
    telefono: "(33) 987-6543",
    horario: "Lunes a Viernes: 8:00 AM - 6:00 PM",
    maps: "https://www.google.com/maps/search/?api=1&query=20.659698,-103.349609",
    fotos: ["https://via.placeholder.com/300x200"],
  },
  {
  nombre: "DentalMás Puebla",
    estado: "Puebla",
    municipio: "Puebla",
    icon: "sun",
    calificacion: 4.5,
    reviews: 70,
    direccion: "Blvd. Atlixco 456, Puebla, PUE",
    telefono: "(222) 123-4567",
    horario: "Lunes a Sábado: 9:00 AM - 7:00 PM",
    maps: "https://www.google.com/maps/search/?api=1&query=Blvd.+Atlixco+456,+Puebla,+PUE",
    fotos: ["https://via.placeholder.com/300x200"],
  },
  {
  nombre: "DentalMás Querétaro",
    estado: "Querétaro",
    municipio: "Querétaro",
    icon: "city",
    calificacion: 4.4,
    reviews: 60,
    direccion: "Av. 5 de Febrero 789, Querétaro, QRO",
    telefono: "(442) 987-6543",
    horario: "Lunes a Viernes: 8:00 AM - 6:00 PM",
    maps: "https://www.google.com/maps/search/?api=1&query=Av.+5+de+Febrero+789,+Querétaro,+QRO",
    fotos: ["https://via.placeholder.com/300x200"],
  },
  {
  nombre: "DentalMás Cancún",
    estado: "Quintana Roo",
    municipio: "Cancún",
    icon: "beach",
    calificacion: 4.3,
    reviews: 50,
    direccion: "Av. Tulum 123, Cancún, QR",
    telefono: "(998) 123-4567",
    horario: "Lunes a Domingo: 9:00 AM - 9:00 PM",
    maps: "https://www.google.com/maps/search/?api=1&query=Av.+Tulum+123,+Cancún,+QR",
    fotos: ["https://via.placeholder.com/300x200"],
  },
  {
  nombre: "DentalMás Mérida",
    estado: "Yucatán",
    municipio: "Mérida",
    icon: "sun",
    calificacion: 4.2,
    reviews: 40,
    direccion: "Av. Montejo 456, Mérida, YUC",
    telefono: "(999) 987-6543",
    horario: "Lunes a Sábado: 9:00 AM - 7:00 PM",
    maps: "https://www.google.com/maps/search/?api=1&query=Av.+Montejo+456,+Mérida,+YUC",
    fotos: ["https://via.placeholder.com/300x200"],
  },
  {
  nombre: "DentalMás León",
    estado: "Guanajuato",
    municipio: "León",
    icon: "city",
    calificacion: 4.1,
    reviews: 30,
    direccion: "Blvd. Campestre 789, León, GTO",
    telefono: "(477) 123-4567",
    horario: "Lunes a Viernes: 8:00 AM - 6:00 PM",
    maps: "https://www.google.com/maps/search/?api=1&query=Blvd.+Campestre+789,+León,+GTO",
    fotos: ["https://via.placeholder.com/300x200"],
  },
  {
  nombre: "DentalMás Toluca",
    estado: "México",
    municipio: "Toluca",
    icon: "city",
    calificacion: 4.0,
    reviews: 20,
    direccion: "Av. Las Torres 123, Toluca, MEX",
    telefono: "(722) 987-6543",
    horario: "Lunes a Sábado: 9:00 AM - 7:00 PM",
    maps: "https://www.google.com/maps/search/?api=1&query=Av.+Las+Torres+123,+Toluca,+MEX",
    fotos: ["https://via.placeholder.com/300x200"],
  },
  {
  nombre: "DentalMás Veracruz",
    estado: "Veracruz",
    municipio: "Veracruz",
    icon: "beach",
    calificacion: 3.9,
    reviews: 15,
    direccion: "Blvd. Ávila Camacho 456, Veracruz, VER",
    telefono: "(229) 123-4567",
    horario: "Lunes a Domingo: 9:00 AM - 9:00 PM",
    maps: "https://www.google.com/maps/search/?api=1&query=Blvd.+Ávila+Camacho+456,+Veracruz,+VER",
    fotos: ["https://via.placeholder.com/300x200"],
  },
  {
  nombre: "DentalMás Morelia",
    estado: "Michoacán",
    municipio: "Morelia",
    icon: "tree",
    calificacion: 3.8,
    reviews: 10,
    direccion: "Av. Madero 789, Morelia, MICH",
    telefono: "(443) 987-6543",
    horario: "Lunes a Viernes: 8:00 AM - 6:00 PM",
    maps: "https://www.google.com/maps/search/?api=1&query=Av.+Madero+789,+Morelia,+MICH",
    fotos: ["https://via.placeholder.com/300x200"],
  },
  {
  nombre: "DentalMás Aguascalientes",
    estado: "Aguascalientes",
    municipio: "Aguascalientes",
    icon: "sun",
    calificacion: 3.7,
    reviews: 8,
    direccion: "Av. López Mateos 123, Aguascalientes, AGS",
    telefono: "(449) 123-4567",
    horario: "Lunes a Sábado: 9:00 AM - 7:00 PM",
    maps: "https://www.google.com/maps/search/?api=1&query=Av.+López+Mateos+123,+Aguascalientes,+AGS",
    fotos: ["https://via.placeholder.com/300x200"],
  },
  {
  nombre: "DentalMás Chihuahua",
    estado: "Chihuahua",
    municipio: "Chihuahua",
    icon: "mountain",
    calificacion: 3.6,
    reviews: 5,
    direccion: "Av. Universidad 456, Chihuahua, CHIH",
    telefono: "(614) 987-6543",
    horario: "Lunes a Domingo: 9:00 AM - 9:00 PM",
    maps: "https://www.google.com/maps/search/?api=1&query=Av.+Universidad+456,+Chihuahua,+CHIH",
    fotos: ["https://via.placeholder.com/300x200"],
  },
  {
  nombre: "DentalMás Hermosillo",
    estado: "Sonora",
    municipio: "Hermosillo",
    icon: "sun",
    calificacion: 3.5,
    reviews: 3,
    direccion: "Blvd. Kino 789, Hermosillo, SON",
    telefono: "(662) 123-4567",
    horario: "Lunes a Viernes: 8:00 AM - 6:00 PM",
    maps: "https://www.google.com/maps/search/?api=1&query=Blvd.+Kino+789,+Hermosillo,+SON",
    fotos: ["https://via.placeholder.com/300x200"],
  },
  // Nueva sucursal en Chiapas
  {
    nombre: "DentalMás Tuxtla",
    estado: "Chiapas",
    municipio: "Tuxtla Gutiérrez",
    icon: "tree",
    calificacion: 4.0,
    reviews: 12,
    direccion: "16.753547,-93.115654",
    telefono: "(961) 123-4567",
    horario: "Lunes a Sábado: 9:00 AM - 7:00 PM",
    maps: "https://www.google.com/maps/search/?api=1&query=16.753547,-93.115654",
    fotos: ["https://via.placeholder.com/300x200"],
  }
];

export { estadosMunicipios };
export default sucursales;
